name: test_messager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  sqlite3_flutter_libs: ^0.5.10
  flutter_launcher_icons: ^0.13.1
  get_it: ^7.7.0
  drift: ^2.2.0
  path_provider: ^2.1.3
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.1.0
  redux: ^5.0.0
  file_picker: ^7.1.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^3.0.0
  drift_dev: ^2.2.0+1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
